#!/bin/sh

# SETTINGS
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config focus_follows_pointer true
bspc config border_width          5
bspc config window_gap	 	  0
bspc config focused_border_color  "#bd93f9"
